#!/bin/sh /etc/rc.common
#
# Copyright (c) 2016 Arduino Srl
# This file is part of Arduino Ciao.

START=20
STOP=20

start() {
    ps w | grep -v grep | grep "ciao-daemon" > /dev/null
    if ! [ $? -eq 0 ]; then
        ciao-daemon &
    fi
}

stop() {
    PID=`/usr/bin/pgrep -f "python -u ciao.py"`
    if [ "x$PID" != "x" ]; then
        /bin/kill -9 $PID
    fi

	killall ciao-daemon
}
